### ISSUE TITLE
Service down

### ISSUE THREAD

**Issue by lclc** [KrzaQ/cppformat#1]
Hi, I was manually converting a few files with your website. Seems that this was too much load, it's down now. Sorry.

**Comment by KrzaQ** [comment]
Restarted. I'll have to stress-test it later, I guess.

**Comment by KrzaQ** [comment]
Well, it hung almost immediately. Switched back to dmd version. Please let me know if it causes you more problems.

**Comment by lclc** [comment]
I've killed it again by trying to format this file with LLVM rules: https://raw.githubusercontent.com/digitalbitbox/mcu/master/tests_unit.c

**Comment by KrzaQ** [comment]
Okay, I can reproduce it. I think it blocks on calling `clang-format` somehow.

**Comment by KrzaQ** [comment]
https://gist.github.com/s-ludwig/8434299
